### ISSUE TITLE
Unify Service Initialization Logging Mechanisms

### ISSUE THREAD

**Issue by debuggin** [wibu-systems/docker-codemeter#4]
We have identified two issues with the current implementation of service initialization and logging mechanisms. Addressing these issues will improve the robustness and transparency of the service whilst making logging consistent.

**Logging Mode Configuration:**
- The logging mode is not available as an environment variable, unlike other CM_ variables. This restricts the flexibility for users to configure logging settings.

**Service Initialization:**
- The initial run of the service when importing a license file uses `-f` rather than `-v` like it should to provide useful output or `-l${loggingMode}`. Consequently, there is no output if an error occurs during license import, making it difficult to diagnose issues.

We propose the following changes:

1. Introduce an environment variable `CM_LOGGING_MODE` (defaultiung to `-`) to configure the logging mode replacing the existing `loggingMode` variable.
2. Modify the initial service start command to include `-l${CM_LOGGING_MODE}` parameters and replace -f with -v. 
3. Modify the `DEFAULT_CM_CMD` to replace `-l${loggingMode}` with `-l${CM_LOGGING_MODE}` 

This ensures logging is enabled from the beginning, providing necessary output for error diagnosis during license import.

**Comment by y-seq** [comment]
This issue will be tracked internally as FB32-100069.
